src/Entity/Planning.php
<?php

namespace App\Entity;

use App\Repository\PlanningRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlanningRepository::class)]
class Planning
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end = null;

    #[ORM\Column(length: 7)]
    private ?string $background_color = null;

    #[ORM\Column(length: 7)]
    private ?string $text_color = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): static
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): static
    {
        $this->end = $end;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): static
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): static
    {
        $this->text_color = $text_color;

        return $this;
    }
}

src/Form/PlanningType.php
<?php

namespace App\Form;

use App\Entity\Planning;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlanningType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', null, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('start', DateTimeType::class, [
                'widget' => 'single_text',
                'attr'   => ['class' => 'form-control'],
            ])
            ->add('end', DateTimeType::class, [
                'widget' => 'single_text',
                'attr'   => ['class' => 'form-control'],
            ])
            ->add('background_color', ColorType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('text_color', ColorType::class, [
                'attr' => ['class' => 'form-control'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Planning::class,
        ]);
    }
}

src/Controller/PlanningController.php
<?php

namespace App\Controller;

use App\Entity\Planning;
use App\Form\PlanningType;
use App\Repository\PlanningRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/planning')]
class PlanningController extends AbstractController
{
    #[Route('/', name: 'app_planning_index', methods: ['GET'])]
    public function index(PlanningRepository $planningRepository): Response
    {
        return $this->render('planning/index.html.twig', [
            'plannings' => $planningRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_planning_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $planning = new Planning();
        $form = $this->createForm(PlanningType::class, $planning);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($planning);
            $entityManager->flush();

            return $this->redirectToRoute('app_planning_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('planning/new.html.twig', [
            'planning' => $planning,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planning_show', methods: ['GET'])]
    public function show(Planning $planning): Response
    {
        return $this->render('planning/show.html.twig', [
            'planning' => $planning,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_planning_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Planning $planning, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlanningType::class, $planning);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_planning_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('planning/edit.html.twig', [
            'planning' => $planning,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planning_delete', methods: ['POST'])]
    public function delete(Request $request, Planning $planning, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$planning->getId(), $request->request->get('_token'))) {
            $entityManager->remove($planning);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_planning_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/planning/_delete_form.html.twig
<form method="post" action="{{ path('app_planning_delete', {'id': planning.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ planning.id) }}">
    <button class="btn btn-danger mt-2">Delete</button>
</form>

templates/planning/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/planning/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Planning{% endblock %}

{% block body %}


    <h1 class="text-dark text-center">Modifier Planning</h1>

    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            {{ include('planning/_form.html.twig', {'button_label': 'Update'}) }}

                {{ include('planning/_delete_form.html.twig') }}

        </div>

    </div>

    <div class="mt-3 text-center">
        <a class="btn btn-secondary" href="{{ path('app_planning_index') }}">Retour à la liste</a>
    </div>



{% endblock %}

templates/planning/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Planning Index{% endblock %}

{% block body %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light p-4">
        <div class="container">
            <a class="navbar-brand" href="{{ path('home') }}">MMA Pulse</a>

            <div class="testNav">
                <ul class="navbar-nav ms-auto">

                    <li class="nav-item">
                        <a class="nav-link mx-2" href="{{ path('home') }}">Home</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>


    <h1 class="text-dark text-center mx-auto">Planning</h1>

    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Start</th>
                <th>End</th>
                <th>Background Color</th>
                <th>Text Color</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for planning in plannings %}
                <tr>
                    <td>{{ planning.id }}</td>
                    <td>{{ planning.title }}</td>
                    <td>{{ planning.start ? planning.start|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ planning.end ? planning.end|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ planning.backgroundColor }}</td>
                    <td>{{ planning.textColor }}</td>
                    <td>
                        <a class="btn btn-primary btn-sm" href="{{ path('app_planning_show', {'id': planning.id}) }}">Voir</a>
                        <a class="btn btn-warning btn-sm" href="{{ path('app_planning_edit', {'id': planning.id}) }}">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">No records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a class="btn btn-success" href="{{ path('app_planning_new') }}">Créer Nouveau</a>

{% endblock %}

templates/planning/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Planning{% endblock %}

{% block body %}



    <div class="container">
        <div class="row vh-100 d-flex justify-content-center mt-5">
            <div class="col-md-8">
                <h1 class="text-dark">Créer nouveau Planning</h1>
                <div class="mb-3">
                    {{ include('planning/_form.html.twig') }}
                </div>
                <div class="mt-3">
                    <a class="btn btn-secondary" href="{{ path('app_planning_index') }}">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/planning/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Planning{% endblock %}

{% block body %}
    <h1 class="text-dark">Planning</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ planning.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ planning.title }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ planning.start ? planning.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ planning.end ? planning.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Background_color</th>
                <td>{{ planning.backgroundColor }}</td>
            </tr>
            <tr>
                <th>Text_color</th>
                <td>{{ planning.textColor }}</td>
            </tr>
        </tbody>
    </table>



    <a href="{{ path('app_planning_index') }}" class="me-2">Retour à la liste</a>

    <a href="{{ path('app_planning_edit', {'id': planning.id}) }}">Modifier</a>

    {{ include('planning/_delete_form.html.twig') }}
{% endblock %}